# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 Catalan Lover <catalanlover@protonmail.com>
#
# This file is part of the REUSE.software compliance configuration.
# It lists the copyright and license information for all files in this directory.
version = 1

[[annotations]]
path = "_category_.json"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "0000A-cycle-review-template.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "0000A-selection.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "2510A-cycle-review.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "2510A-selection.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"
