# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 Catalan Lover <catalanlover@protonmail.com>
#
# This file is part of the REUSE.software compliance configuration.
# It lists the copyright and license information for all files in this directory.
version = 1

[[annotations]]
path = "renovate.json5"
SPDX-FileCopyrightText = "2024 Aminda Suomalainen <suomalainen@aminda.eu>"
SPDX-License-Identifier = "CC0-1.0"
