# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 Catalan Lover <catalanlover@protonmail.com>
#
# This file is part of the REUSE.software compliance configuration.
# It lists the copyright and license information for all files in this directory.
version = 1

[[annotations]]
path = ".cspell.json"
SPDX-FileCopyrightText = [
	"2025 David Harder <david@davidjharder.ca>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = ".cspell-allowed-words"
SPDX-FileCopyrightText = [
	"2025 David Harder <david@davidjharder.ca>",
	"2025 Gnuxie <Gnuxie@protonmail.com>"
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = ".editorconfig"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = ".gitattributes"
SPDX-FileCopyrightText = [
	"2024 Catlan Lover <catalanlover@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = ".gitignore"
SPDX-FileCopyrightText = [
	"2024 Catlan Lover <catalanlover@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = ".pre-commit-config.yaml"
SPDX-FileCopyrightText = [
	"2024, 2026 Catlan Lover <catalanlover@protonmail.com>",
	"2025 Gnuxie <Gnuxie@protonmail.com>"
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "babel.config.js"
SPDX-FileCopyrightText = "2024 Facebook Inc"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "docusaurus.config.ts"
SPDX-FileCopyrightText = [
    "2024 Facebook Inc",
	"2024 - 2026 Catlan Lover <catalanlover@protonmail.com>",
	"2024 Gnuxie <Gnuxie@protonmail.com>",
    "2025 MTRNord <support@midnightthoughts.space>"
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "package.json"
SPDX-FileCopyrightText = [
    "2024 Facebook Inc",
	"2024 - 2026 Catlan Lover <catalanlover@protonmail.com>",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "2024 Facebook Inc"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "sidebars.ts"
SPDX-FileCopyrightText = [
    "2024 Facebook Inc",
	"2025 MTRNord <support@midnightthoughts.space>",
]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tsconfig.json"
SPDX-FileCopyrightText = "2024 Facebook Inc"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "yarn.lock"
SPDX-FileCopyrightText = [
    "2024 Facebook Inc",
	"2024 - 2026 Catlan Lover <catalanlover@protonmail.com>",
]
SPDX-License-Identifier = "MIT"
