import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import apisidebar from './docs/api/sidebar';

/**
 * This is generated by the docusaurus template that we chose from.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  mainSidebar: [
    { type: 'autogenerated', dirName: '.' },
    {
      type: 'category',
      label: 'API Specification',
      items: apisidebar,
      link: {
        type: 'doc',
        id: 'api/draupnir-api',
      }
    },
  ],

};

export default sidebars;
