import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * This is copied directly from the docusauros tutorial.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
