# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: 2026 Catalan Lover <catalanlover@protonmail.com>
#
# This file is part of the REUSE.software compliance configuration.
# It lists the copyright and license information for all files in this directory.
version = 1

[[annotations]]
path = "_category_.json"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "ethical-values.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "governance.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "groups.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "inspiration.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "longhouse-consultation.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "longhouse-cycle.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"

[[annotations]]
path = "longhouse-presentation.md"
SPDX-FileCopyrightText = [
	"2025 Gnuxie <Gnuxie@protonmail.com>",
]
SPDX-License-Identifier = "AFL-3.0"
